# Generated by Django 2.2.12 on 2020-04-18 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.College'),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.College'),
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.College'),
        ),
    ]
